---
title: "BCCWJ-SPR OT 試行実験"
author: "Masayuki Asahara"
date: "2021/02/19"
output:
  html_document:
    toc: true
    toc_float: true    
---

# 準備
## ファイル読み込み
```{r reading_file}
d = read.table("OT-masked.txt",sep="\t",header=TRUE,fileEncoding="UTF-8")
d$SPR_subj_ID_factor = as.factor(d$SPR_subj_ID)
d$SPR_log_reading_time = log(d$SPR_reading_time)
d$BCCWJ_OT_school_type = substring(d$BCCWJ_Sample_ID, 1, 4)
head(d)
summary(d)
```

## 頻度主義的モデリング
### ライブラリ読み込み
```{r reading_library, echo=FALSE}
library(lme4)
library(stargazer)
```

### 全体のデータを使ってモデリング（読み時間）：
```{r model_all}
model_all <- lmer(SPR_reading_time~SPR_sentence_ID+SPR_bunsetsu_ID+SPR_word_length+SPR_trial+BCCWJ_OT_school_type+(1|SPR_subj_ID_factor)+(1|BCCWJ_Sample_ID),data=d,REML=FALSE)
summary(model_all)
save(model_all,file="OT_model.obj")
stargazer(model_all)
stargazer(model_all,type="text")
```
3SD より外側を削除してモデリング（読み時間）：
```{r model_trim_3sd}
d_trim = d[scale(resid(model_all)) < 3.0 , ]
nrow(d) - nrow(d_trim)
(nrow(d) - nrow(d_trim)) / nrow(d)
model_trim = lmer(SPR_reading_time~SPR_sentence_ID+SPR_bunsetsu_ID+SPR_word_length+SPR_trial+BCCWJ_OT_school_type+(1|SPR_subj_ID_factor)+(1|BCCWJ_Sample_ID),data=d_trim,REML=FALSE)
summary(model_trim)
save(model_trim,file="OT_model_trim.obj")
stargazer(model_trim,type="latex")
```

### 全体のデータを使ってモデリング（対数読み時間）：
```{r log_model_all}
log_model_all = lmer(SPR_log_reading_time~SPR_sentence_ID+SPR_bunsetsu_ID+SPR_word_length+SPR_trial+BCCWJ_OT_school_type+(1|SPR_subj_ID_factor)+(1|BCCWJ_Sample_ID),data=d,REML=FALSE)
summary(log_model_all)
save(log_model_all,file="OT_log_model.obj")
stargazer(log_model_all,type="text")
```
3SD より外側を削除してモデリング（対数読み時間）：
```{r log_model_trim_3sd}
d_trim_log = d[scale(resid(log_model_all)) < 3.0 , ]
nrow(d) - nrow(d_trim_log)
(nrow(d) - nrow(d_trim_log)) / nrow(d)
log_model_trim = lmer(SPR_log_reading_time~SPR_sentence_ID+SPR_bunsetsu_ID+SPR_word_length+SPR_trial+BCCWJ_OT_school_type+(1|SPR_subj_ID_factor)+(1|BCCWJ_Sample_ID),data=d_trim_log,REML=FALSE)
summary(log_model_trim)
save(log_model_trim,file="OT_log_model_trim.obj")
stargazer(log_model_trim,type="text")
```

