---
title: "BCCWJ-SPR OW 試行実験"
author: "Masayuki Asahara"
date: "2021/02/19"
output:
  html_document:
    toc: true
    toc_float: true    
---

# 準備
## ファイル読み込み
```{r reading_file}
d = read.table("OW-unmasked.txt",sep="\t",header=TRUE,fileEncoding="UTF-8")
d$SPR_subj_ID_factor = as.factor(d$SPR_subj_ID)
d$SPR_log_reading_time = log(d$SPR_reading_time)
head(d)
summary(d)
```

## 頻度主義的モデリング
### ライブラリ読み込み
```{r reading_library, echo=FALSE}
library(lme4)
library(stargazer)
```

### 全体のデータを使ってモデリング（読み時間）：
```{r model_all}
model_all = lmer(SPR_reading_time~SPR_sentence_ID+SPR_bunsetsu_ID+SPR_word_length+DepPara_depnum+(1|SPR_subj_ID_factor),data=d,REML=FALSE)
summary(model_all)
stargazer(model_all)
```
3SD より外側を削除してモデリング（読み時間）：
```{r model_trim_3sd}
d_trim = d[scale(resid(model_all)) < 3.0 , ]
nrow(d) - nrow(d_trim)
(nrow(d) - nrow(d_trim)) / nrow(d)
model_trim = lmer(SPR_reading_time~SPR_sentence_ID+SPR_bunsetsu_ID+SPR_word_length+DepPara_depnum+(1|SPR_subj_ID_factor),data=d_trim,REML=FALSE)
summary(model_trim)
stargazer(model_trim)
```

### 全体のデータを使ってモデリング（対数読み時間）：
```{r log_model_all}
log_model_all = lmer(SPR_log_reading_time~SPR_sentence_ID+SPR_bunsetsu_ID+SPR_word_length+DepPara_depnum+(1|SPR_subj_ID_factor),data=d,REML=FALSE)
summary(log_model_all)
```
3SD より外側を削除してモデリング
```{r log_model_trim_3sd}
d_trim_log = d[scale(resid(log_model_all)) < 3.0 , ]
nrow(d) - nrow(d_trim_log)
(nrow(d) - nrow(d_trim_log)) / nrow(d)
log_model_trim = lmer(SPR_log_reading_time~SPR_sentence_ID+SPR_bunsetsu_ID+SPR_word_length+DepPara_depnum+(1|SPR_subj_ID_factor),data=d_trim_log,REML=FALSE)
summary(log_model_trim)
```

## ベイズ主義的モデリング

### ライブラリ読み込み
```{r reading_stan_library, eval=FALSE}
library(rstan)
rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores())
```
```{r setwd, eval=FALSE}
setwd("/Users/masayu-a/Desktop/2021-01-15-SPR/")
```
### ベイズ分析

```{r stanDat, eval=FALSE}
stanDat <- list(time=d$SPR_reading_time,
	sentid=d$SPR_sentence_ID,
	bid=d$SPR_bunsetsu_ID,
	length=d$SPR_word_length,
	dependent=d$DepPara_depnum,
	subjid=d$SPR_subj_ID,
	N = nrow(d),
	N_subj=length(unique(d$SPR_subj_ID)))
```

```{r stan, eval=FALSE}
model.fit <- stan(file="07OW.stan", data = stanDat, iter = 1000, chain = 3, warmup= 100)
save(model.fit,file="model-OW.obj")
```

```{r shinystan, eval=FALSE}
library(shinystan)
launch_shinystan(model.fit)
```
